### ISSUE TITLE
Setup sponsorship page

### ISSUE THREAD

**Issue by webtaculars** [webtaculars-com/yt-extension#1]
Update sponsorship page with Buymeacoffee link

**Comment by shehrozsheikh** [comment]
I like the idea of this extension and I can take care of this, but I was wondering you want to create a separate sponsorship page or we can simply add a small BuyMeACoffee button in the Browser Action Popup (options.html) in the footer maybe like this one?
![image](https://user-images.githubusercontent.com/17910552/96337389-3b432500-10a0-11eb-8788-60b4ad74dd59.png) 

It will be more visible to the users, if you've got any better ideas please share.

**Comment by janusz01** [comment]
We can do something like this:

![YPM BMC](https://user-images.githubusercontent.com/36551654/96338553-924ef700-10ac-11eb-8c4f-7730c3c1e0e7.png)

Keep margin of about 50px between the apply button and this section.

Here's the snippet:
<script type="text/javascript" src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" data-name="bmc-button" data-slug="webtaculars" data-color="#FF5F5F" data-emoji=""  data-font="Cookie" data-text="Buy me a coffee" data-outline-color="#000" data-font-color="#fff" data-coffee-color="#fd0" ></script>

OR

Image Code:
<a href="https://www.buymeacoffee.com/webtaculars" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-red.png" alt="Buy Me A Coffee" style="height: 60px !important;width: 217px !important;" ></a>

Use whatever is needed!

**Comment by shehrozsheikh** [comment]
Looks good to me @janusz01. Can you please assign it to me?

**Comment by shehrozsheikh** [comment]
Just created a PR for this, please check: https://github.com/webtaculars-com/youtube-productivity-mode/pull/5

**Comment by webtaculars** [comment]
Closing this as  #5 is merged. Thanks @shehrozsheikh
