### ISSUE TITLE
Channel Page and History Page option not working

### ISSUE THREAD

**Issue by janusz01** [webtaculars-com/yt-extension#3]
Instead, they are getting handled by "Trending Page" option.

**Comment by shehrozsheikh** [comment]
I found the bug, please assign it to me.

**Comment by shehrozsheikh** [comment]
Subscription page option is not working either, but it's the same bug.

**Comment by shehrozsheikh** [comment]
Just created a PR -> https://github.com/webtaculars-com/youtube-productivity-mode/pull/6

**Comment by webtaculars** [comment]
Closed as per the above PR
